LTD-2407 Content changes
uktrade/lite-api pull request #1027
Opened 2022-06-23 21:40 UTC by seijihg

2022-06-27 04:26 UTC, saruniitr commented on api/audit_trail/formatters.py
> +    if status == CaseStatusEnum.APPLICANT_EDITING.replace("_", " "):
what is the reason to replace `_` with space?

2022-06-27 04:27 UTC, saruniitr commented on api/audit_trail/formatters.py
> +    if status == "re-opened for changes":
similarly here, you can use `REOPENED_FOR_CHANGES` correct?

2022-06-27 20:41 UTC, seijihg commented on api/audit_trail/formatters.py
> +    if status == CaseStatusEnum.APPLICANT_EDITING.replace("_", " "):
just to convert it back from "applicant_editing" to this (APPLICANT_EDITING, "Applicant editing") lower cased
` 
payload={
                "status": {
                    "new": CaseStatusEnum.get_text(case_status.status),
                    "old": CaseStatusEnum.get_text(old_status.status),
                },
                "additional_text": data.get("note"),
            },
`

since status is getting converted with CaseStatusEnum.get_text(case_status.status)

2022-06-28 08:09 UTC, saruniitr commented on api/audit_trail/formatters.py
> +    if status == CaseStatusEnum.APPLICANT_EDITING.replace("_", " "):
Just use the status value directly instead of calling `CaseStatusEnum.get_text()` then you will get the correct value in this function, as below,
```
        payload={
            "status": {
                "new": CaseStatusEnum.SUBMITTED,
                "old": old_status,
            }
        },
```

You need to do this all places where this event is used and handle all status in the formatter function `get_updated_status()`

2022-06-29 11:37 UTC, saruniitr requested changes

2022-06-29 11:37 UTC, saruniitr commented on api/staticdata/statuses/enums.py
> +        (REOPENED_FOR_CHANGES, "Reopened for changes"),
this change is not required

2022-06-29 11:37 UTC, saruniitr commented on api/audit_trail/formatters.py
> +
please remove this blank line

2022-06-29 12:48 UTC, saruniitr submitted a review, later dismissed

2022-06-29 14:51 UTC, saruniitr approved these changes

2022-06-29 14:51 UTC, merged