LTD-4840-remove-flags
uktrade/lite-api pull request #1925
Opened 2024-04-16 12:12 UTC by seijihg

Continue on this other PR got a bit messy for some reason:

https://github.com/uktrade/lite-api/pull/1879

https://uktrade.atlassian.net/browse/LTD-4840

Current idea that we’re investigating:
- new table that contains the flags to remove
- new method to remove the flag
- new method to remove the audit trail
- new method that runs on finalisation to run the remove flag and audit trail notes

2024-04-22 08:41 UTC, Tllew approved these changes
Looks good to me

2024-04-22 13:36 UTC, saruniitr requested changes
I think this can be improved and also best to deploy to an env first and see it runs without any issues.

2024-04-22 13:36 UTC, saruniitr commented on api/cases/management/commands/removes_flags.py
> +        self.stdout.write(self.style.SUCCESS(f"Successfully adjusted {count} cases."))
Please use logging and also update to use old style formatting of strings for logs instead of f-strings because these are evaluated immediately whereas old style formatting is lazy and depending on the loglevel there may not be a need to evaluate them.

2024-04-22 13:36 UTC, saruniitr commented on api/flags/views.py
> +                    "added_flags_id": self.added_flags_id,
Is this really required? we already have flag name which can be used.
One other problem with adding this is that old audit log entries won't have this field and they will be left out.

2024-04-22 15:20 UTC, seijihg commented on api/cases/libraries/finalise.py
> +            case.flags.remove(flag)
wow this is a clean one! cheers

2024-04-22 15:27 UTC, seijihg commented on api/cases/libraries/finalise.py
> +    flags_to_remove_ids = [str(flag_id) for flag_id in flags_to_remove_ids]  # Convert UUIDs to strings
thanks great one!

2024-04-22 15:42 UTC, seijihg commented on api/cases/management/commands/removes_flags.py
> +        for case in Case.objects.all():
for some reason i did not thing about this lol

2024-04-22 15:43 UTC, seijihg commented on api/cases/management/commands/removes_flags.py
> +        self.stdout.write(self.style.SUCCESS(f"Successfully adjusted {count} cases."))
this is just printing out some info after command finished running I am not sure if we need `logger = logging.getLogger(__name__)` for this.

2024-04-22 15:47 UTC, seijihg commented on api/flags/views.py
> +                    "added_flags_id": self.added_flags_id,
yes first version we did match via name but Kevin had a different thought about it since we did not want to remove the log where people casually mention about or in the future we may have similiar flags name etc etc so its just safer to go via IDs. From the SPIKE there is nothing in the audit trails to remove (UAT DB) for the ones we are required atm.

2024-04-22 15:48 UTC, seijihg commented on api/cases/management/commands/removes_flags.py
> +                remove_flags_from_audit_trail(case)
done! thanks

2024-04-23 11:00 UTC, saruniitr commented on api/flags/views.py
> +                    "added_flags_id": self.added_flags_id,
Actually we cannot assign flags manually from UI so this will never be called.
Flags are only added by flagging rules.

One other problem in my previous comment is that old audit log entries won't have this field and they will be left out.

2024-04-23 16:19 UTC, seijihg commented on api/cases/management/commands/tests/test_removes_flags_and_audits_from_cases.py
> +        flag = Flag.objects.get(id=self.original_flag_id)
I was just checking how many flags is there and only original exists since the test one was deleted.

2024-04-23 16:29 UTC, seijihg commented on api/cases/tests/test_finalise_advice.py
> +        self.assertEqual(case.flags.first(), flag)
updated like above to make it easier to read.

2024-04-23 16:32 UTC, seijihg commented on api/flags/views.py
> +                    "added_flags_id": self.added_flags_id,
reference to slack comment.

2024-04-24 15:34 UTC, saruniitr approved these changes

2024-04-25 09:26 UTC, merged