Ltd 4935 migration to populate entity type
uktrade/lite-api pull request #1936
Opened 2024-04-19 14:39 UTC by markj0hnst0n

### Aim

Populate new DenialEntity entity_type field as a choice of 3 strings End-user, Consignee or Third Party based on json data currently stored in the data field.

[LTD-4935](https://uktrade.atlassian.net/browse/LTD-4935)

2024-04-22 11:06 UTC, hnryjmes commented on api/external_data/migrations/0023_set_denial_entity_type.py
> +# import logging
you can get rid of these if they're not being used anymore

2024-04-22 11:11 UTC, hnryjmes commented on api/external_data/migrations/0023_set_denial_entity_type.py
> +        and isinstance(normalised_entity_type_dict["other_role"], str)
(this isn't a suggestion to change anything, just a comment)

I'm not sure how this bit of the code should behave if the value for `other_role` is an empty string. it seems like what we have here in this block is going to run if there's any value in that column including it being empty.

maybe if that's what we want we can communicate that more simply by not making this bit an `elif` and just using `else`. what do you think?

2024-04-22 11:14 UTC, hnryjmes commented on api/external_data/migrations/0023_set_denial_entity_type.py
> +        denial_entity.save()
once this is committed to dev branch it will run as a migration every time the full set of migrations are run, and it seems to be that it's only really the first time that we need to set `entity_type`.

do we definitely want to set it based on the `data` dict each time the migration is run? if it just needs to be run once, maybe this bit of code can be conditional on `entity_type` not already existing on the found `DenialEntity` object which might make the migration quicker to run as it will be able to skip objects that don't need updating in future.

2024-04-22 11:16 UTC, hnryjmes reviewed
looks good to me, happy to approve after you've had a chance to respond to the other comments

2024-04-22 14:46 UTC, saruniitr requested changes

2024-04-22 14:46 UTC, saruniitr commented on api/external_data/migrations/0023_set_denial_entity_type.py
> +def get_denial_entity_type(data):
I think retrieving the value and also checking at the same time in conditions is making it hard to follow, especially the same thing being repeated in all conditions.
Please consider something like below to simplify,
```
entity_type_dict = {key.lower(): value.lower() for key, value in data.items()}

is_end_user = entity_type_dict.get('end_user_flag', 'false') == 'true'
is_consignee = entity_type_dict.get('consignee_flag', 'false') == 'true'
is_third_party = entity_type_dict.get('other_role', 'false') == 'true'

if is_end_user:
    entity_type = DenialEntityType.END_USER
if is_consignee:
    entity_type = DenialEntityType.CONSIGNEE

# noticed below in the data so we need to handle this as well
if is_end_user and is_consignee:
    entity_type = DenialEntityType.END_USER.   # please verify what is required here.

if is_third_party:
    entity_type = DenialEntityType.THIRD_PARTY
```

Also please add if there are any other combinations

2024-04-22 14:46 UTC, saruniitr commented on api/external_data/migrations/0023_set_denial_entity_type.py
> +    for denial_entity in DenialEntity.objects.all():
is `DenialEntity.objects.filter(entity_type__isnull=True)` better?

2024-04-22 14:46 UTC, saruniitr commented on api/external_data/tests/test_0023_set_denial_entity_type.py
> +        "data": {"END_USER_FLAG": "true", "CONSIGNEE_FLAG": "false", "OTHER_ROLE": ""},
data indicates both `end_user_flag` and `consignee_flag` can be true so please test for that as well.

2024-04-22 15:17 UTC, saruniitr commented on api/external_data/migrations/0023_set_denial_entity_type.py
> +        denial_entity.save()
For the first time this may still take quite a lot of time as `entity_type` is not set.
We can actually query based on fields in json data as well, perhaps best to investigate a bit where by querying fields within json `data` if we can filter all end_users, consginee etc then we can just `update()` with one query rather than `save()` for each item.

2024-04-22 15:28 UTC, markj0hnst0n commented on api/external_data/tests/test_0023_set_denial_entity_type.py
> +        "data": {"END_USER_FLAG": "true", "CONSIGNEE_FLAG": "false", "OTHER_ROLE": ""},
I've used:

`class DenialEntityType:
    CONSIGNEE = "consignee"
    END_USER = "end_user"
    THIRD_PARTY = "third_party"

    choices = ((CONSIGNEE, "Consignee"), (END_USER, "End-user"), (THIRD_PARTY, "Third party"))
`
as the 3 options for the DenialEntity.entity_type.  Would it be appropriate to use one of them or give another field?
@saruniitr @depsiatwal

2024-04-22 15:30 UTC, markj0hnst0n commented on api/external_data/migrations/0023_set_denial_entity_type.py
> +        and isinstance(normalised_entity_type_dict["other_role"], str)
The unit tests I wrote tested for this scenario and you're right it does produce a "Third-Party" result with an empty string.  Should the response be something else?

2024-04-22 15:37 UTC, markj0hnst0n commented on api/external_data/migrations/0023_set_denial_entity_type.py
> +def get_denial_entity_type(data):
Not sure what the output should be for end_user_flag and consignee_flag both being true.  Have queried below

2024-04-22 15:37 UTC, saruniitr commented on api/external_data/tests/test_0023_set_denial_entity_type.py
> +        "data": {"END_USER_FLAG": "true", "CONSIGNEE_FLAG": "false", "OTHER_ROLE": ""},
No, it is not about adding another option.
If both end_user_flag and consignee_flag is 'true' then I think that is case where consignee and end-user are the same or there is no consignee so the entity_type is most likely 'end-user' in this case.
I think this needs to be discussed with UCD/business on how SPIRE uses these fields.

2024-04-22 15:41 UTC, markj0hnst0n commented on api/external_data/tests/test_0023_set_denial_entity_type.py
> +        "data": {"END_USER_FLAG": "true", "CONSIGNEE_FLAG": "false", "OTHER_ROLE": ""},
I see.  Thanks!

2024-04-22 15:50 UTC, depsiatwal commented on api/external_data/migrations/0023_set_denial_entity_type.py
> +        denial_entity.save()
hmmm why would it run every time ?
you mean locally ? when we migrate

2024-04-23 08:21 UTC, markj0hnst0n commented on api/external_data/migrations/0023_set_denial_entity_type.py
> +        denial_entity.save()
@saruniitr  I've made changes based on this comment.  I think I have implemented what you mean!  Although maybe it should have an else statement which populates with an empty string after to prevent the code below the for statement firing every time?

2024-04-23 08:23 UTC, markj0hnst0n commented on api/external_data/tests/test_0023_set_denial_entity_type.py
> +        "data": {"END_USER_FLAG": "true", "CONSIGNEE_FLAG": "false", "OTHER_ROLE": ""},
made amendments based on this but will seek further guidance

2024-04-23 08:57 UTC, depsiatwal commented on api/external_data/tests/test_0023_set_denial_entity_type.py
> +        "data": {"END_USER_FLAG": "true", "CONSIGNEE_FLAG": "false", "OTHER_ROLE": ""},
@markj0hnst0n  can you reach out to Collin Harrall to get some more assistance ?

2024-04-23 14:31 UTC, saruniitr reviewed
Thanks for your patience.
This is looking good, just need clarifications on the other_role conditions.

2024-04-23 14:31 UTC, saruniitr commented on api/external_data/migrations/0023_set_denial_entity_type.py
> +    elif is_end_user_flag == False and is_consignee_flag == False and third_party_string_has_value == True:
`third_party_string_has_value` is always going to be `True` here because all of the fields values are strings.
I guess you only want this to be True if that is a non-empty string correct?

Looking at the data for 'other_role' there are no consistent values for this field.
Eg there is 'Not specified' also, so in this case can this be considered as third party?
I think this also need to be discussed with UCD.

2024-04-23 14:31 UTC, saruniitr commented on api/external_data/migrations/0023_set_denial_entity_type.py
> +    third_party_string_has_value = isinstance(normalised_entity_type_dict["other_role"], str)
```
other_role = normalised_entity_type_dict.get("other_role", "")
```

then further down you can check whether it is empty/not-empty etc and add conditions accordingly.

2024-04-23 14:31 UTC, saruniitr commented on api/external_data/tests/test_0023_set_denial_entity_type.py
> +        assert DenialEntity.objects.filter(entity_type="third_party").count() == 1
we could use the same enums `DenialEntityType` here as well.

2024-04-23 15:01 UTC, markj0hnst0n commented on api/external_data/tests/test_0023_set_denial_entity_type.py
> +        assert DenialEntity.objects.filter(entity_type="third_party").count() == 1
done!

2024-04-23 15:01 UTC, markj0hnst0n commented on api/external_data/migrations/0023_set_denial_entity_type.py
> +    third_party_string_has_value = isinstance(normalised_entity_type_dict["other_role"], str)
I think I've implemented this in a slightly different way

2024-04-24 08:19 UTC, depsiatwal commented on api/external_data/migrations/0023_set_denial_entity_type.py
> +    normalised_entity_type_dict = {keys.lower(): values.lower() for keys, values in data.items()}
What would happen here if data is none I think we need to check to make sure data is a dict else migration would fail.

2024-04-24 09:02 UTC, saruniitr approved these changes
looks good to me.

2024-04-24 09:23 UTC, hnryjmes approved these changes

2024-04-24 10:18 UTC, merged