LTD-5306 added reversion to parties
uktrade/lite-api pull request #2135
Opened 2024-08-13 07:48 UTC by Tllew

[LTD-5306](https://uktrade.atlassian.net/browse/LTD-5306)

[LTD-5306]: https://uktrade.atlassian.net/browse/LTD-5306?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-08-13 08:07 UTC, markj0hnst0n approved these changes

2024-08-13 08:08 UTC, hnryjmes requested changes
please can you add tests

2024-08-13 14:27 UTC, saruniitr commented on api/parties/models.py
>  class Party(TimestampableModel, Clonable):
it needs tests to check versions are being created when we change object

2024-08-14 09:39 UTC, hnryjmes approved these changes
this looks much better with tests. the test coverage checks both that it is possible to create versions and that versions are created automatically when the Party object is updated.

2024-08-14 10:57 UTC, merged