Allow caseworker and exporter to download document
uktrade/lite-api pull request #651
Opened 2020-11-05 17:27 UTC by richtier

2020-11-05 17:38 UTC, r4vi approved these changes

2020-11-06 16:53 UTC, r4vi requested changes
just looked at this again and had a thought about enumeration attacks / brute forcing document IDs

2020-11-06 16:53 UTC, r4vi commented on api/documents/views.py
> +    authentication_classes = (SharedAuthentication,)
Question about this - if I figure out a random document ID do I end up with the ability to download an arbitrary document?
Do we need something in the vein of "django object permissions" to ensure that if you are an exporter user you can only download your own ones and not "any" document ?

2020-11-09 09:35 UTC, richtier commented on api/documents/views.py
> +    authentication_classes = (SharedAuthentication,)
I'll check :+1:

2020-11-09 11:10 UTC, r4vi approved these changes

2020-11-09 15:44 UTC, merged