Add FOI reason field
uktrade/lite-api pull request #653
Opened 2020-11-20 11:12 UTC by eadpearce

2020-11-27 10:58 UTC, saruniitr requested changes

2020-11-27 10:58 UTC, saruniitr commented on api/applications/models.py
> +    foi_reason = models.TextField(blank=True, null=True)
Documentation suggests avoid using `null=True` for string-based fields,
https://docs.djangoproject.com/en/3.1/ref/models/fields/#null

2021-01-05 15:49 UTC, eadpearce commented on api/applications/models.py
> +    foi_reason = models.TextField(blank=True, null=True)
Fixed!

2021-01-05 15:54 UTC, r4vi approved these changes

2021-01-05 16:58 UTC, merged