Generates report for summary of applications finalised
uktrade/lite-api pull request #727
Opened 2021-03-10 12:35 UTC by saruniitr

2021-03-10 12:45 UTC, saruniitr commented on api/reports/queries/standard.py
> +        , concat(ct.reference, ' ', '(', sa.export_type, ')') "Application type formatted"
how to select this in the final output starting at line479

2021-03-10 17:41 UTC, r4vi requested changes

2021-03-10 17:41 UTC, r4vi commented on api/reports/management/commands/reports.py
> +    "standard_apx   plications_goods_and_ratings": GOODS_AND_RATINGS,
typo?

2021-03-10 17:41 UTC, r4vi commented on api/reports/queries/standard.py
> +(select string_agg(distinct goods.good_desc, ',') from goods where goods.application_id = applications.case_id) "Description",
we split good description and name didn't we? we should `concat` the description and name here

2021-03-10 17:41 UTC, r4vi commented on api/reports/queries/standard.py
> +(select string_agg(cast((goods.good_quantity - goods.licence_usage) as text), ',') from goods where goods.application_id = applications.case_id) "Licence Remaining quantities",
I think this is correct

2021-03-10 17:59 UTC, saruniitr commented on api/reports/queries/standard.py
> +(select string_agg(cast((goods.good_quantity - goods.licence_usage) as text), ',') from goods where goods.application_id = applications.case_id) "Licence Remaining quantities",
:+1:

2021-03-10 18:05 UTC, saruniitr commented on api/reports/management/commands/reports.py
> +    "standard_apx   plications_goods_and_ratings": GOODS_AND_RATINGS,
yes, fixed.

2021-03-10 19:23 UTC, saruniitr commented on api/reports/queries/standard.py
> +(select string_agg(distinct goods.good_desc, ',') from goods where goods.application_id = applications.case_id) "Description",
yeah this is not updated, adding name to get `name: description` and aggregate over all goods in that application

2021-03-10 19:27 UTC, r4vi commented
you could do it in the goods table, where you create "goods_desc" so this
bit can remain unchanged

On Wed, Mar 10, 2021 at 7:23 PM Arun Siluvery <notifications@github.com>
wrote:

> *@saruniitr* commented on this pull request.
> ------------------------------
>
> In api/reports/queries/standard.py
> <https://github.com/uktrade/lite-api/pull/727#discussion_r591805105>:
>
> > +) select
> +applications.case_type "Case type",
> +applications.export_type "Export type",
> +applications.licensee "Licensee",
> +applications.intended_end_use "End use",
> +applications.agreed_to_foi "FOI Objection flag",
> +applications.foi_reason "FOI Objection",
> +applications.submitted_at "Submitted Datetime",
> +applications.last_closed_at "Closed Datetime",
> +licences.status "Licence status",
> +(select string_agg(distinct advices.type, ',') from advices where advices.case_id = applications.case_id) "Outcome",
> +(select string_agg(distinct goods.report_summary, ',') from goods where goods.application_id = applications.case_id) "Goods Ars",
> +(select string_agg(distinct goods.ratings, ',') from goods where goods.application_id = applications.case_id) "Goods Rating",
> +(select string_agg(cast((goods.good_quantity - goods.licence_usage) as text), ',') from goods where goods.application_id = applications.case_id) "Licence Remaining quantities",
> +(select sum(goods.good_value) from goods where goods.application_id = applications.case_id) "Total Goods value",
> +(select string_agg(distinct goods.good_desc, ',') from goods where goods.application_id = applications.case_id) "Description",
>
> yeah this is not updated, adding name to get name: description and
> aggregate over all goods in that application
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/uktrade/lite-api/pull/727#discussion_r591805105>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAEKC7C4OCU3L6YYJZI4T7TTC7BMRANCNFSM4Y55NWQQ>
> .
>

2021-03-11 09:50 UTC, r4vi approved these changes

2021-03-11 15:50 UTC, merged