Require exporter comments when not attaching a document to Good
uktrade/lite-api pull request #847
Opened 2021-11-02 12:37 UTC by Pithikos

2021-11-03 23:58 UTC, saruniitr requested changes

2021-11-03 23:58 UTC, saruniitr commented on api/goods/models.py
> +        max_length=2000,
You don't need to specify max length for `TextField`, please remove, also we don't want to limit it to the user.

2021-11-03 23:58 UTC, saruniitr commented on api/goods/tests/test_document_reasons.py
> +        [[{"is_document_available": "yes"}], [{"is_document_available": "no", "no_document_comments": "yada yada"}]]
Please add sensible test data instead of above
eg datasheet not available or similar

2021-11-03 23:58 UTC, saruniitr commented on api/goods/tests/test_document_reasons.py
> +        data = {"is_document_available": "no", "no_document_comments": "yada yada yada"}
same as above

2021-11-04 08:31 UTC, saruniitr commented on api/goods/serializers.py
> -                    firearm_details=firearm_details, instance=instance.firearm_details,
I think we need `no_document_comments` in `GoodCreateSerializer` above at line 350

2021-11-04 09:01 UTC, wkeeling commented on api/goods/serializers.py
> +        allow_null=False, error_messages={"invalid": "Enter the products date of issue and include a day, month, year."}
Minor grammar: "products" should be "product's"

2021-11-04 09:34 UTC, wkeeling commented on api/goods/views.py
>      def get(self, request, pk):
Wondering whether this be a `post` endpoint now that it's going to be receiving a block of text for the `no_document_comments`?

2021-11-04 09:59 UTC, Pithikos commented on api/goods/serializers.py
> +        allow_null=False, error_messages={"invalid": "Enter the products date of issue and include a day, month, year."}
Good catch. This was just the linter, but I'll change it since I don't want to be git-blamed for poor grammar :')

2021-11-04 10:30 UTC, Pithikos commented on api/goods/serializers.py
> -                    firearm_details=firearm_details, instance=instance.firearm_details,
True, I think this is not caught by the test coverage since we actually don't seem to call serializer's `is_valid()` at least in the step I was working on

2021-11-05 12:28 UTC, saruniitr approved these changes
lgtm, thanks

2021-11-05 12:35 UTC, merged