LTD-1368
uktrade/lite-api pull request #857
Opened 2021-11-11 12:57 UTC by Pithikos

2021-11-17 15:23 UTC, alixedi requested changes
Left some initial comments.

2021-11-17 15:23 UTC, alixedi commented on api/applications/models.py
> +        choices=ApplicationExportLicenceOfficialType.choices, blank=True, null=True, default=None, max_length=50
Was `black` complaining about this @Pithikos ?

(this comment applies to a bunch of changes in this file)

2021-11-17 15:23 UTC, alixedi commented on api/conftest.py
> +# -------------------------- Clients ----------------------------
This is not necessary I reckon.

2021-11-17 15:23 UTC, alixedi commented on api/conftest.py
> +class LiteClient(APIClient):
What is the use for this in the API?

Elsewhere, we are using the standard Django test client and it works well.

2021-11-17 16:51 UTC, Pithikos commented on api/conftest.py
> +# -------------------------- Clients ----------------------------
You mean the header? Yeah, just put it since it's different things in the same conftest so makes it easier to split into separate files in the future

2021-11-18 13:47 UTC, Pithikos commented on api/applications/models.py
> +        choices=ApplicationExportLicenceOfficialType.choices, blank=True, null=True, default=None, max_length=50
Yep, as discussed on Slack, the pre-commit hook was using a different version of black and auto-formatting the file. I've added a fix for this on this PR.

I think it's fine to keep the changes. `black` won't fix it back (from what I tested locally)

2021-11-22 12:29 UTC, eadpearce commented on api/documents/models.py
> +    is_content_english = models.NullBooleanField(help_text="Is the document in English?")
^ what the doc said

2021-11-22 12:37 UTC, eadpearce commented on api/conftest.py
> +        return super().get(*args, **kwargs, **self.headers)
do we need all these methods in here if they're just doing the same as the superclass?

2021-11-22 12:38 UTC, eadpearce commented on api/conftest.py
> +        return super().get(*args, **kwargs, **self.headers)
ah wait. is `self.headers` the different part?

2021-11-22 12:41 UTC, eadpearce commented on api/parties/serializers.py
> +                raise serializers.ValidationError({"is_content_english": "Required field"})
based on the help text we have for these fields a better error message could be "Select yes if the document is in English"

2021-11-22 12:42 UTC, eadpearce commented on api/parties/serializers.py
> +                raise serializers.ValidationError({"includes_company_letterhead": "Required field"})
"Select yes if the document includes at least one page on company letterhead"

2021-11-22 13:22 UTC, Pithikos commented on api/conftest.py
> +        return super().get(*args, **kwargs, **self.headers)
Yep, essentially the whole client just sets the right headers once `login()` is called

2021-11-22 16:09 UTC, merged

2021-11-23 09:51 UTC, alixedi commented on api/conftest.py
> +        return super().get(*args, **kwargs, **self.headers)
Did you not see this on the superclass @Pithikos ?

```
    def credentials(self, **kwargs):
        """
        Sets headers that will be used on every outgoing request.
        """
        self._credentials = kwargs
```