Sporting Shotgun (code) references removed
uktrade/lite-api pull request #862
Opened 2021-11-18 15:53 UTC by nahmed99

2021-11-18 16:27 UTC, saruniitr reviewed
There are many unrelated formatting issues. This could be mainly because your `black` version is different. Please use the correct version to not make these changes.
Please check with @Pithikos , he had similar problem and corrected it now.

2021-11-25 10:17 UTC, eadpearce approved these changes
lgtm

2021-11-25 10:32 UTC, saruniitr commented on api/goods/helpers.py
> +        organisation=organisation_id, document_type=document_type
these unrelated black formatting changes need to be reverted

2021-11-25 10:34 UTC, saruniitr requested changes
Please remove unrelated black formatting changes, there are many to ignore.

2021-11-25 12:54 UTC, nahmed99 commented on api/goods/helpers.py
> +        organisation=organisation_id, document_type=document_type
Done.

2021-11-25 13:35 UTC, saruniitr approved these changes
ty, looks good to me now

2021-11-25 13:57 UTC, merged