Backwards compatible SIEL location flow updates
uktrade/lite-api pull request #885
Opened 2021-12-15 12:28 UTC by eadpearce

2021-12-16 13:48 UTC, wkeeling commented on api/applications/models.py
> +    export_type = models.TextField(choices=ApplicationExportType.choices, blank=True, default="")
We need to update `LITEStandardApplicationsPipeline` in the reports repo, and switch the `export_type` to be a `Text` type there too (it's currently a `String` type of maxlen 50). I'll raise a ticket.

2021-12-16 13:58 UTC, wkeeling approved these changes
Looks good to me - perhaps worth squashing the commits before merging though?

2021-12-16 13:59 UTC, wkeeling approved these changes
Looks good to me - perhaps worth squashing the commits before merging though?

2021-12-16 14:42 UTC, alixedi requested changes
Can you please clean up the commits before I review this?

2021-12-16 18:35 UTC, saruniitr commented on api/applications/views/applications.py
> +        update_serializer = get_application_update_serializer(application)
`partial=True` implies update so this renaming is not necessary

2021-12-17 09:40 UTC, eadpearce commented on api/applications/views/applications.py
> +        update_serializer = get_application_update_serializer(application)
this was only renamed because there's another variable further down called serializer and it's less confusing this way

2021-12-31 10:10 UTC, merged